/*
This file is part of PatternExtractor v0.3

PatternExtractor is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PatternExtractor is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with PatternExtractor.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * TileViewer.java
 *
 * Created on Jan 1, 2006, 1:28:22 AM
 */
package com.deepak.patternextractor.gui;

import com.deepak.patternextractor.core.Tile;
import java.awt.Dimension;
import java.awt.Graphics;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author deepak
 */

/*
 * TileViewer.java
 *
 * this jpanel class is used for displaying the tile image in the main window
 */
public class TileViewer extends javax.swing.JPanel implements PropertyChangeListener {

    // tile refference
    private Tile tile = null;

    /** Creates new form ImageViewer */
    public TileViewer() {
        initComponents();
    }

    /*
     * getter method to get the tile refference
     */
    public Tile getTile() {
        return tile;
    }

    /*
     * setter method to set the tile refference
     */
    public void setTile(Tile tile) {
        // set tile refference
        this.tile = tile;
        // add the current class(TileViewer) as the tile property change listner
        this.tile.addPropertyChangeListener(this);
        // resize the tile viewer panel componet to the size of the tile
        this.setPreferredSize(new Dimension(tile.getWidth(), tile.getHeight()));
        // revalidate the tile viewer component
        this.revalidate();
        // repaint the component
        this.repaint();
    }

    /*
     * overidden paint method of the jpanel
     */
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        // if the tile is present then
        if (tile != null) {
            // draw the tile image onto the panel
            g.drawImage(tile.getTileImage(), 0, 0, this);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /*
     * propertyChange method implemented asper PropertyChangeListener interface
     */
    public void propertyChange(PropertyChangeEvent evt) {
        // resizing the tile viewer panel to the tile image resolutions
        this.setPreferredSize(new Dimension(tile.getWidth(), tile.getHeight()));
        // revalidating the tile viewer component
        this.revalidate();
        // repaint the panel
        this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
